"use client";
import { useEffect,useState } from "react";
import { useSession,signOut } from "next-auth/react";
import { PushManager,usePush } from "@/components/PushManager";
import { requestJson,jsonOptions,errorMessage } from "@/lib/client-api";
export default function Settings(){
 const {data:session,update}=useSession(),push=usePush();
 const [profile,setProfile]=useState<{name:string;departmentId:string|null}|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;if(session?.user?.id)requestJson<{name:string;departmentId:string|null}>("/api/users/"+session.user.id).then(data=>{if(active)setProfile(data);}).catch(e=>{if(active)setError(errorMessage(e));});return()=>{active=false;};},[session?.user?.id]);
 return <div className="max-w-3xl mx-auto space-y-6"><h1 className="text-2xl font-semibold">Settings</h1>{error&&<p role="alert" className="text-red-400">{error}</p>}{message&&<p role="status" className="text-green-400">{message}</p>}{profile?<form className="panel space-y-4" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,fields=new FormData(form);setError("");setMessage("");setBusy(true);try{const newPassword=String(fields.get("newPassword"));if(newPassword!==String(fields.get("confirmPassword")))throw new Error("New passwords do not match");const result=await requestJson<{signInRequired:boolean}>("/api/profile",jsonOptions("PATCH",{name:fields.get("name"),departmentId:fields.get("departmentId"),currentPassword:fields.get("currentPassword")||undefined,newPassword:newPassword||undefined}));if(result.signInRequired){try{await push.detach();}catch{}await signOut({callbackUrl:"/login"});return;}await update();setMessage("Profile saved");}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}>
 <label className="block">Name<input className="field" name="name" required maxLength={160} defaultValue={profile.name}/></label><label className="block">Department<input className="field" name="departmentId" maxLength={80} defaultValue={profile.departmentId??""}/></label><p className="text-neutral-400">{session?.user?.email} ? {session?.user?.role}</p><fieldset className="space-y-3"><legend className="font-medium">Change password (optional)</legend><label className="block">Current password<input className="field" type="password" name="currentPassword" maxLength={72} autoComplete="current-password"/></label><label className="block">New password<input className="field" type="password" name="newPassword" minLength={12} maxLength={72} autoComplete="new-password"/></label><label className="block">Confirm new password<input className="field" type="password" name="confirmPassword" minLength={12} maxLength={72} autoComplete="new-password"/></label><p className="text-sm text-neutral-400">Changing your password signs out all sessions.</p></fieldset><button className="btn" disabled={busy}>Save changes</button></form>:<p>Loading profile?</p>}<section className="panel"><h2 className="font-medium mb-3">Desktop notifications</h2><PushManager/></section></div>;
}