"use client";
import { useState } from "react";
import Link from "next/link";
import { signIn } from "next-auth/react";
import { useRouter } from "next/navigation";
import { requestJson,jsonOptions,errorMessage } from "@/lib/client-api";
export default function Register(){
 const router=useRouter(),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 return <main className="min-h-screen bg-neutral-950 text-neutral-100 px-4 py-16"><div className="max-w-md mx-auto space-y-5"><h1 className="text-3xl font-semibold">Create an employee account</h1><p className="text-neutral-400">Staff accounts are provisioned by an administrator.</p><form className="panel space-y-4" onSubmit={async e=>{e.preventDefault();const fields=new FormData(e.currentTarget);const email=String(fields.get("email")).trim().toLowerCase(),password=String(fields.get("password"));setBusy(true);setError("");try{await requestJson("/api/register",jsonOptions("POST",{name:fields.get("name"),email,password,departmentId:fields.get("departmentId")}));const result=await signIn("credentials",{email,password,redirect:false});if(result?.error){router.push("/login");return;}router.push("/");router.refresh();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}>
 {error&&<p role="alert" className="text-red-400">{error}</p>}<label className="block">Name<input className="field" name="name" autoComplete="name" required maxLength={160}/></label><label className="block">Email<input className="field" type="email" name="email" autoComplete="email" required/></label><label className="block">Password<input className="field" type="password" name="password" autoComplete="new-password" required minLength={12} maxLength={72}/><span className="text-sm text-neutral-400">12?72 characters. Use a unique passphrase.</span></label><label className="block">Department<input className="field" name="departmentId" maxLength={80}/></label><button className="btn" disabled={busy}>{busy?"Creating?":"Create account"}</button></form><Link className="text-indigo-400" href="/login">Already registered? Sign in</Link></div></main>;
}